### ISSUE TITLE
getting permission denied 

### ISSUE THREAD

**Issue by koineramitranjan** [ramanandapanda/fabric-sdk-kvs-vault#5]
When trying to read from kvs using loadUserFromStateStore...I am getting permission denied. Is there some additional settings that needs to be done?

**Comment by rp01** [comment]
@koineramitranjan, sorry for the delay.
can you please put some more information regarding this.
A screenshot will be helpful.

**Comment by koineramitranjan** [comment]
Hi,

Thanks following is the message on console:
 VaultKVS Enter Constructor, options are {"endpoint":"http://127.0.0.1:8200","token":"s.aRqmeWq6eeXH3neNzeuBw5s8","apiVersion":"v1"} +0ms
  VaultKVS getValue with name admin +649ms
  VaultKVS retrive data form the vault +76ms
  VaultKVS getValue error permission denied +24ms
Failed to enroll admin: Error: permission denied

Following the code :
fabric_client.loadUserFromStateStore('admin');

Vault server start:
==> Vault server configuration:

             Api Address: http://127.0.0.1:8200
                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8201
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "disabled")
               Log Level: info
                   Mlock: supported: false, enabled: false
                 Storage: inmem
                 Version: Vault v1.0.3
             Version Sha: 85909e3373aa743c34a6a0ab59131f61fd9e8e43

WARNING! dev mode is enabled! In this mode, Vault runs entirely in-memory
and starts unsealed with a single unseal key. The root token is already
authenticated to the CLI, so you can immediately begin using Vault.

You may need to set the following environment variable:

    $ export VAULT_ADDR='http://127.0.0.1:8200'

The unseal key and root token are displayed below in case you want to
seal/unseal the Vault or re-authenticate.

Unseal Key: +7uMMBNCJiqjf3SAs4DJM35fuJwKI8nYntU43wp9744=
Root Token: s.aRqmeWq6eeXH3neNzeuBw5s

I can do read and write through console. But when I am trying to read its throwing aforementioned error. Thanks for your help

**Comment by rp01** [comment]
@koineramitranjan try to run 
export VAULT_TOKEN=s.aRqmeWq6eeXH3neNzeuBw5s
and check.
Probably it is due to wrong access token.
or you can pass token in the <network.yaml> file

**Comment by koineramitranjan** [comment]
I have exported the VAULT_TOKEN
Do you have sample code for using this with fabric client and the policy that you have set. Will be really thankful if you can share it. I think I am making a mistake somewhere

**Comment by rp01** [comment]
> I have exported the VAULT_TOKEN
> Do you have sample code for using this with fabric client and the policy that you have set. Will be really thankful if you can share it. I think I am making a mistake somewhere

@koineramitranjan 
https://github.com/ramanandapanda/balance-transfer-vault

**Comment by rp01** [comment]
@koineramitranjan I also have updated the script with better debug message.
Please pull the latest code.

**Comment by koineramitranjan** [comment]
thanks a lot..let me check out

**Comment by rp01** [comment]
I am closing this issue.

**Comment by koineramitranjan** [comment]
thanks Ramanan! i pulled in the code have exported the token ..but still am getting  No authorization token was found...

**Comment by koineramitranjan** [comment]
in app.js there is thisismysecret is it something that i need to replace

**Comment by rp01** [comment]
@koineramitranjan 
No,
first, u need to enrol admin.

- To do so first you need to start the application by ./runApp.sh
- Then in postman post /users with {username:"admin",orgName:"Org1"} //one the organisation in the network-config.yaml file. You will get an error first stating admin already exists.
- Then post the same and you will get the admin JWTToken in the response.
- after that user the jwt token in the header to do other activities.
For reference please check the following link from hyperledger.
https://github.com/hyperledger/fabric-samples/tree/release/balance-transfer

**Comment by koineramitranjan** [comment]
Thanks for your help...
I am not sure what I doing wrong.....I have exported both VAULT_TOKEN as well VAULT_ADDR , I can confirm its set by reading it using echo...I have also set it in org1.yaml...I have started the runApp.sh when trying to hit the api using the /users I get "UnauthorizedError: No authorization token was found"
Am I missing something obvious? 
Vault version : Vault v1.0.3

**Comment by koineramitranjan** [comment]
Some more information when running /testAPI.sh i get following error trace:"
[2019-02-25 12:18:49.668] [DEBUG] Helper - [FabricCAClientService.js]: Successfully constructed Fabric CA service client: endpoint - {"protocol":"https","hostname":"localhost","port":8054}
[2019-02-25 12:18:49.721] [DEBUG] Helper - [utils.CryptoKeyStore]: This class requires a CryptoKeyStore to save keys, using the store: {"opts":{"endpoint":"http://127.0.0.1:8300","token":"s.cHdQtplGnyn0qFlXeiZFriBc","apiVersion":"v1"}}
  VaultKVS Enter Constructor, options are {"endpoint":"http://127.0.0.1:8300","token":"s.cHdQtplGnyn0qFlXeiZFriBc","apiVersion":"v1"} +56ms
  VaultKVS options { endpoint: 'http://127.0.0.1:8300',
  token: 's.cHdQtplGnyn0qFlXeiZFriBc',
  apiVersion: 'v1' } +0ms
[2019-02-25 12:18:49.723] [DEBUG] Helper - [utils.CryptoKeyStore]: _getKeyStore returning ks
[2019-02-25 12:18:49.723] [DEBUG] Helper - [crypto_ecdsa_aes]: generateKey, store.setValue
[2019-02-25 12:18:49.723] [DEBUG] Helper - [ecdsa/key.js]: ECDSA curve param X: e4155edaaed5c4dde5b799c8e5d65dcb07638c34070e43821503c46d820e0eab
[2019-02-25 12:18:49.723] [DEBUG] Helper - [ecdsa/key.js]: ECDSA curve param Y: 4079ab4fbc6df08250855baa9d2abff5e91503354fe32961d56f238e52c753c9
  VaultKVS setValue with name aa3c1b3261a2f8e269a8b752537474ed6eae860280e586e54cdace06204e70d3-priv +3ms
  VaultKVS setValue error permission denied +6ms
[2019-02-25 12:18:49.731] [ERROR] Helper - [FabricCAClientService.js]: Failed to enroll admin, error:Error: Failed to generate key for enrollment due to error [Error: permission denied]

**Comment by rp01** [comment]
@koineramitranjan 
first u need to ```post``` to /users
{
	"username":"admin",
	"orgName":"Org1"
}
in return u will get error first time.
you need to post again and u will get a similar response
{
    "success": true,
    "secret": "",
    "message": "admin enrolled Successfully",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NTExMTM2MjYsInVzZXJuYW1lIjoiYWRtaW4iLCJvcmdOYW1lIjoiT3JnMSIsImlhdCI6MTU1MTA3NzYyNn0.raPBE_uZaPExGt_QtIMmdXJhJ8644LkOcED9xDoXokE"
}
![image](https://user-images.githubusercontent.com/6177511/53319478-a30b9180-38f8-11e9-91e4-6bd01c72444e.png)

**Comment by koineramitranjan** [comment]
thanks am getting the following error now, have tried hitting the API multiple times:
2019-02-25 12:29:55.063] [DEBUG] Helper - [ecdsa/key.js]: ECDSA curve param Y: 770a40d291bab7acbc89ee1b724c31ebb03bec3c5b3b69368eec51705784268c
  VaultKVS setValue with name 0e44ae8e76d30264648edb51b3e7e947d87d3d090c9f4e7d2ebb9897fcdb3e92-priv +3ms
  VaultKVS setValue error permission denied +7ms

At the postman side:
2019-02-25 12:29:55.063] [DEBUG] Helper - [ecdsa/key.js]: ECDSA curve param Y: 770a40d291bab7acbc89ee1b724c31ebb03bec3c5b3b69368eec51705784268c
  VaultKVS setValue with name 0e44ae8e76d30264648edb51b3e7e947d87d3d090c9f4e7d2ebb9897fcdb3e92-priv +3ms
  VaultKVS setValue error permission denied +7ms

Do i need to do some setup on the vault side? I am currently running it in dev mode (./vault server -dev)

**Comment by rp01** [comment]
> Some more information when running /testAPI.sh i get following error trace:"
> [2019-02-25 12:18:49.668] [DEBUG] Helper - [FabricCAClientService.js]: Successfully constructed Fabric CA service client: endpoint - {"protocol":"https","hostname":"localhost","port":8054}
> [2019-02-25 12:18:49.721] [DEBUG] Helper - [utils.CryptoKeyStore]: This class requires a CryptoKeyStore to save keys, using the store: {"opts":{"endpoint":"[http://127.0.0.1:8300","token":"s.cHdQtplGnyn0qFlXeiZFriBc","apiVersion":"v1"}}](http://127.0.0.1:8300%22,%22token%22:%22s.cHdQtplGnyn0qFlXeiZFriBc%22,%22apiVersion%22:%22v1%22%7D%7D)
> VaultKVS Enter Constructor, options are {"endpoint":"[http://127.0.0.1:8300","token":"s.cHdQtplGnyn0qFlXeiZFriBc","apiVersion":"v1"}](http://127.0.0.1:8300%22,%22token%22:%22s.cHdQtplGnyn0qFlXeiZFriBc%22,%22apiVersion%22:%22v1%22%7D) +56ms
> VaultKVS options { endpoint: 'http://127.0.0.1:8300',
> token: 's.cHdQtplGnyn0qFlXeiZFriBc',
> apiVersion: 'v1' } +0ms
> [2019-02-25 12:18:49.723] [DEBUG] Helper - [utils.CryptoKeyStore]: _getKeyStore returning ks
> [2019-02-25 12:18:49.723] [DEBUG] Helper - [crypto_ecdsa_aes]: generateKey, store.setValue
> [2019-02-25 12:18:49.723] [DEBUG] Helper - [ecdsa/key.js]: ECDSA curve param X: e4155edaaed5c4dde5b799c8e5d65dcb07638c34070e43821503c46d820e0eab
> [2019-02-25 12:18:49.723] [DEBUG] Helper - [ecdsa/key.js]: ECDSA curve param Y: 4079ab4fbc6df08250855baa9d2abff5e91503354fe32961d56f238e52c753c9
> VaultKVS setValue with name aa3c1b3261a2f8e269a8b752537474ed6eae860280e586e54cdace06204e70d3-priv +3ms
> VaultKVS setValue error permission denied +6ms
> [2019-02-25 12:18:49.731] [ERROR] Helper - [FabricCAClientService.js]: Failed to enroll admin, error:Error: Failed to generate key for enrollment due to error [Error: permission denied]

@koineramitranjan you are getting "setValue error permission denied" means u are using wrong token for vault.
you need to export in the same tab where you are running the sample project.
further please PM me
https://www.linkedin.com/in/ramananda-panda/

**Comment by koineramitranjan** [comment]
thanks a lot!...figured it out after sending the comment! thanks once again!

**Comment by rp01** [comment]
> thanks a lot!...figured it out after sending the comment! thanks once again!

@koineramitranjan 
what went wrong?
Please explain. I am curious.

**Comment by koineramitranjan** [comment]
Earlier problems got resolved by your suggestion. The last one was due to wrong token being exported.
